// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDB4XpC3gIrGtp8KVQYKCFvOaJvZqo62I',
    appId: '1:629360479250:web:f5e78438eb5d9ebf8a9ccb',
    messagingSenderId: '629360479250',
    projectId: 'camera-e454d',
    authDomain: 'camera-e454d.firebaseapp.com',
    databaseURL: 'https://camera-e454d-default-rtdb.firebaseio.com',
    storageBucket: 'camera-e454d.appspot.com',
    measurementId: 'G-W4THJGLNJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4vzGp7-Q0rxWcUUkORZ6gyfq_uqwx_YM',
    appId: '1:629360479250:android:735423dc45fb45738a9ccb',
    messagingSenderId: '629360479250',
    projectId: 'camera-e454d',
    databaseURL: 'https://camera-e454d-default-rtdb.firebaseio.com',
    storageBucket: 'camera-e454d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpzNS07rv0mU35UegR7e-soF9jZ-35Xo',
    appId: '1:629360479250:ios:ed238ba4be6605ea8a9ccb',
    messagingSenderId: '629360479250',
    projectId: 'camera-e454d',
    databaseURL: 'https://camera-e454d-default-rtdb.firebaseio.com',
    storageBucket: 'camera-e454d.appspot.com',
    iosClientId: '629360479250-7v8jrq92sk4mk3hvsuuuo09rm9au1co4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvpzNS07rv0mU35UegR7e-soF9jZ-35Xo',
    appId: '1:629360479250:ios:ed238ba4be6605ea8a9ccb',
    messagingSenderId: '629360479250',
    projectId: 'camera-e454d',
    databaseURL: 'https://camera-e454d-default-rtdb.firebaseio.com',
    storageBucket: 'camera-e454d.appspot.com',
    iosClientId: '629360479250-7v8jrq92sk4mk3hvsuuuo09rm9au1co4.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDB4XpC3gIrGtp8KVQYKCFvOaJvZqo62I',
    appId: '1:629360479250:web:b36553e2c3691f738a9ccb',
    messagingSenderId: '629360479250',
    projectId: 'camera-e454d',
    authDomain: 'camera-e454d.firebaseapp.com',
    databaseURL: 'https://camera-e454d-default-rtdb.firebaseio.com',
    storageBucket: 'camera-e454d.appspot.com',
    measurementId: 'G-6WLQCRLZK4',
  );

}